version: '3.7'
services:
  #Nginx Service
  webserver:
    image: nginx:1.19.3
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
      # - "443:443"
    volumes:
      # - ./src:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-network

  #backend Service
  backend:
    image: nginx:1.19.3
    container_name: backend
    restart: unless-stopped

    # ports:
    #   - "80:80"
      # - "443:443"
    volumes:
      - ./src/index.html:/usr/share/nginx/html/index.html
            
    networks:
      - nginx-network

#Docker Networks
networks:
  nginx-network:
    name: nginx-network