version: '3.7'
services:
  #webserver Service
  webserver:
    image: nginx:1.19.3
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
      # - "443:443"
    volumes:
      # - ./src:/usr/share/nginx/html
      - ./webserver/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-network

  #backend Service
  backend-1:
    image: nginx:1.19.3
    container_name: backend-1
    restart: unless-stopped

    volumes:
      - ./backend-1/src/index.html:/usr/share/nginx/html/index.html
      - ./backend-1/nginx/default.conf:/etc/nginx/conf.d/default.conf
            
    networks:
      - nginx-network

#Docker Networks
networks:
  nginx-network:
    name: nginx-network